### ISSUE TITLE
Request to add manhwareader.com

### ISSUE THREAD

**Issue by worstgamedev** [yuru-yuri/manga-py#189]
# Request to add a site

Description | Other site for manhwa or webtoons
---|---
Url to add | https://manhwareader.com/

**Comment by 1271** [comment]
I close it.
If you have any difficulties, do not hesitate to create a new issue.

**Comment by gromenauer** [comment]
Seems to redirect to `https://hentaihand.com/`

**Comment by 1271** [comment]
> Seems to redirect to `https://hentaihand.com/`

Oh. A couple of days ago it worked as it should :-(

**Comment by 1271** [comment]
I am closing this issue.
If you still have questions, open a new one.
Thank )
